
Artist.create!(name: 'Maya Freelon', location: 'Durham, NC ', gender: 'Female', age: '90+', facebook: '', tumblr: '', instagram: 'https://www.instagram.com/mayafreelon/', twitter: '')
Artist.create!(name: 'Keenan Kshlerin', location: 'South Carolina', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Fletcher Fadel', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.comartist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Mickey Bins', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Dede Bailey DDS', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.comartist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Jason Nicolas', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Vita Klein', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Norbert Weissnat', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Gilda Jakubowski', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Adrianne Hagenes', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Chauncey Lang V', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Ms. Daysi Bechtelar', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Patrica Adams', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Miss Joey Harvey', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Andree Reichert', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Thanh Hills', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Wiley Lebsack', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Argelia Huels', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Romaine Cassin', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Miss Shayne Deckow', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Tyson Torp Jr.', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Breana Mayert', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Kellie Labadie', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Colton Bednar', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Dr. Teodoro Wilkinson', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Gerard Herman', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Kimiko Pouros', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Allen Nikolaus', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Cleveland Johnson', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Mr. Loida Monahan', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Lennie Stamm', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: 'instagram.com/test', twitter: '')
  Artist.create!(name: 'Domenic Emard', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Alina Balistreri DDS', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Huey Wilderman', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Tami Ferry IV', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Rea Kohler', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Beverlee Kilback MD', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Fred Krajcik', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Hilma Dooley', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Sandy Okuneva', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Bruno Jaskolski', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
  Artist.create!(name: 'Arletha Strosin', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Britt Howell', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Arletta Runolfsson', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Priscila Lebsack', location: '', gender: 'Male', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Harland Schowalter', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Mr. Nilda Wilderman', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Edison Fadel', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Johnsie Wisozk I', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Albert Casper', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Fritz Koelpin MD', location: '', gender: 'Female', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Mrs. Geraldo Heathcote', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Mr. Bret McCullough', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Kathlene OKeefe DVM', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.com/artist99', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Garry Schoen MD', location: '', gender: 'Female', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/janet', instagram: '', twitter: '')
Artist.create!(name: 'Ms. Joshua Labadie', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Argentina Haag', location: '', gender: 'Male', age: '26 to 40', facebook: 'http://www.facebook.com/jamesbobosmith', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
Artist.create!(name: 'Cesar Kuvalis', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
  Artist.create!(name: 'Dana Spencer MD', location: '', gender: 'Male', age: '90+', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/asdf', instagram: '', twitter: '')
Artist.create!(name: 'Cedric Kozey', location: '', gender: 'Female', age: '25 and under', facebook: 'http://www.facebook.com/gina', tumblr: 'http://www.tumblr.com/bbobsart', instagram: '', twitter: '')
  Artist.create!(name: 'Masodn', location: '', gender: 'Male', age: '', facebook: '', tumblr: '', instagram: 'asdf', twitter: '')
Artist.create!(name: 'Hebru Brantley', location: '', gender: 'Male', age: '38', facebook: '', tumblr: '', instagram: '', twitter: '')
